name: 'test'
description: 'test'

inputs:
  test-input:
    description: 'sdfsdfsdf'
    required: true
    default: 'World'

outputs:
  time:
    description: 'output description'

runs:
  using: 'composite'
  steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' 

    - name: Run PHP script
      shell: bash
      run: php index.php
      env:
        TEST_INPUT: ${{ inputs.test-input }}
