name: 'test'
description: 'test'

inputs:
  test-input:
    description: 'sdfsdfsdf'
    required: true
    default: 'World'

outputs:
  time:
    description: 'output description'

runs:
  using: 'php'
  main: 'index.php'

