name: 'test'
description: 'test'

inputs:
  test-input:
    description: 'sdfsdfsdf'
    required: true
    default: 'World'

runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/entrypoint.sh'
  args:
    - ${{ inputs.test-input }}

